<?php

/**
 * @file
 * Layout Builder Example module.
 */

declare(strict_types = 1);

/**
 * Implements hook_plugin_filter_TYPE__CONSUMER_alter().
 */
function layout_builder_examples_plugin_filter_block__layout_builder_alter(array &$definitions): void {
  // Filter the available blocks in Layout Builder.
  $definitions = array_filter($definitions, function (string $plugin_id): bool {
    $allowed_plugin_ids = [
      '^layout_builder_examples',
      '^views_block',
    ];

    foreach ($allowed_plugin_ids as $allowed_plugin_id) {
      if (preg_match("~{$allowed_plugin_id}~", $plugin_id)) {
        return TRUE;
      }
    }

    return FALSE;
  }, ARRAY_FILTER_USE_KEY);

  // Do a final pass to explicitly remove any blocks we still don't want after
  // filtering them above.
  $disallowed_plugin_ids = [
    'views_block:content_recent-block_1',
    'views_block:who_s_new-block_1',
    'views_block:who_s_online-who_s_online_block',
  ];

  foreach ($disallowed_plugin_ids as $disallowed_plugin_id) {
    unset($definitions[$disallowed_plugin_id]);
  }
}

/**
 * Implements hook_plugin_filter_TYPE__CONSUMER_alter().
 */
function layout_builder_examples_plugin_filter_layout__layout_builder_alter(array &$definitions): void {
  $definitions = array_filter($definitions, function (string $plugin_id): bool {
    return (bool) preg_match('/^layout_builder_examples/', $plugin_id);
  }, ARRAY_FILTER_USE_KEY);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function layout_builder_examples_form_layout_builder_add_block_alter(array &$form, FormStateInterface $form_state): void {
  // Make the block title a hidden element and generate a UUID for the block
  // title if one is not already provided.
  $form['settings']['label']['#type'] = 'hidden';
  $uuid = Drupal::service('uuid')->generate();
  $label_default_value = $form['settings']['label']['#default_value'] ?: $uuid;
  $form['settings']['label']['#default_value'] = $label_default_value;

  // Make the label display checkbox hidden and always set the value to false.
  $form['settings']['label_display']['#type'] = 'hidden';
  $form['settings']['label_display']['#default_value'] = FALSE;
}
